# Copyright (c) 2025-2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

"""Auto-generated by isaaclab_arena.llm_env_gen.

Task: Pick up the avocado from the table and place it in the bowl.

Task wiring: PickAndPlaceTask: pick_up=avocado, destination=bowl
"""

from __future__ import annotations

import argparse
from typing import TYPE_CHECKING

from isaaclab_arena.assets.register import register_environment
from isaaclab_arena_environments.example_environment_base import ExampleEnvironmentBase

if TYPE_CHECKING:
    from isaaclab_arena.environments.isaaclab_arena_environment import IsaacLabArenaEnvironment


@register_environment
class AvocadoPnPBowlTableEnvironment(ExampleEnvironmentBase):
    """Pick up the avocado from the table and place it in the bowl."""

    name: str = "avocadoPnPbowltable"

    def get_env(self, args_cli: argparse.Namespace) -> IsaacLabArenaEnvironment:
        from isaaclab_arena.assets.object_base import ObjectType
        from isaaclab_arena.assets.object_reference import ObjectReference
        from isaaclab_arena.environments.isaaclab_arena_environment import IsaacLabArenaEnvironment
        from isaaclab_arena.relations.relations import In, IsAnchor, Not, On, PositionLimits
        from isaaclab_arena.scene.scene import Scene
        from isaaclab_arena.tasks.pick_and_place_task import PickAndPlaceTask
        from isaaclab_arena.utils.pose import Pose

        background = self.asset_registry.get_asset_by_name("maple_table_robolab")()
        background.set_initial_pose(Pose(position_xyz=(0.5, 0.0, 0.0), rotation_xyzw=(0.0, 0.0, 0.7071068, 0.7071068)))
        ground_plane = self.asset_registry.get_asset_by_name("ground_plane")()
        ground_plane.set_initial_pose(Pose(position_xyz=(0.0, 0.0, -1.05)))
        light = self.asset_registry.get_asset_by_name("light")()

        # Tabletop anchor — tabletop anchor = tabletop_anchor (ObjectReference sub-prim); PositionLimits derived from get_world_bounding_box().
        tabletop_anchor = ObjectReference(
            name="table",
            prim_path="{ENV_REGEX_NS}/maple_table_robolab/table",
            parent_asset=background,
            object_type=ObjectType.RIGID,
        )
        tabletop_anchor.add_relation(IsAnchor())

        # Runtime-derived XY footprint from the tabletop bbox — no
        # hardcoded bounds, works across tables of any size. The
        # bbox stores (N, 3) tensors; we squeeze to plain floats
        # for the first env since PositionLimits takes scalars and
        # the tabletop is static across envs.
        _tbl_bbox = tabletop_anchor.get_world_bounding_box()
        _tbl_min_xyz = [float(_tbl_bbox.min_point[0, i]) for i in range(3)]
        _tbl_max_xyz = [float(_tbl_bbox.max_point[0, i]) for i in range(3)]
        _tbl_margin = 0.05

        # No kwargs — works for both no_embodiment and robot embodiments whose
        # optional flags (enable_cameras, etc.) default to safe values.
        embodiment = self.asset_registry.get_asset_by_name(args_cli.embodiment)()

        # Robot placement sampled on tabletop edge 'x_max' at fraction 0.448;
        # base sits 0.1 m outside the edge, yaw faces the table center.
        _robot_x = _tbl_max_xyz[0] + 0.1
        _robot_y = (1 - 0.4481) * _tbl_min_xyz[1] + 0.4481 * _tbl_max_xyz[1]
        embodiment.set_initial_pose(
            Pose(
                position_xyz=(_robot_x, _robot_y, 0.0),
                rotation_xyzw=(0.0, 0.0, 1.0, 0.0),
            )
        )

        avocado_obj = self.asset_registry.get_asset_by_name("avocado01_fruits_veggies_robolab")()
        bowl_obj = self.asset_registry.get_asset_by_name("bowl_ycb_robolab")()
        broccoli_obj = self.asset_registry.get_asset_by_name("broccoli")()
        sweet_potato_obj = self.asset_registry.get_asset_by_name("sweet_potato")()
        red_bell_pepper_obj = self.asset_registry.get_asset_by_name("red_bell_pepper_objaverse_robolab")()

        avocado_obj.add_relation(On(tabletop_anchor, clearance_m=0.02))
        avocado_obj.add_relation(
            PositionLimits(
                x_min=_tbl_min_xyz[0] + _tbl_margin,
                x_max=_tbl_max_xyz[0] - _tbl_margin,
                y_min=_tbl_min_xyz[1] + _tbl_margin,
                y_max=_tbl_max_xyz[1] - _tbl_margin,
            )
        )
        avocado_obj.add_relation(Not(In(bowl_obj)))
        bowl_obj.add_relation(On(tabletop_anchor, clearance_m=0.02))
        bowl_obj.add_relation(
            PositionLimits(
                x_min=_tbl_min_xyz[0] + _tbl_margin,
                x_max=_tbl_max_xyz[0] - _tbl_margin,
                y_min=_tbl_min_xyz[1] + _tbl_margin,
                y_max=_tbl_max_xyz[1] - _tbl_margin,
            )
        )
        broccoli_obj.add_relation(On(tabletop_anchor, clearance_m=0.02))
        broccoli_obj.add_relation(
            PositionLimits(
                x_min=_tbl_min_xyz[0] + _tbl_margin,
                x_max=_tbl_max_xyz[0] - _tbl_margin,
                y_min=_tbl_min_xyz[1] + _tbl_margin,
                y_max=_tbl_max_xyz[1] - _tbl_margin,
            )
        )
        sweet_potato_obj.add_relation(On(tabletop_anchor, clearance_m=0.02))
        sweet_potato_obj.add_relation(
            PositionLimits(
                x_min=_tbl_min_xyz[0] + _tbl_margin,
                x_max=_tbl_max_xyz[0] - _tbl_margin,
                y_min=_tbl_min_xyz[1] + _tbl_margin,
                y_max=_tbl_max_xyz[1] - _tbl_margin,
            )
        )
        red_bell_pepper_obj.add_relation(On(tabletop_anchor, clearance_m=0.02))
        red_bell_pepper_obj.add_relation(
            PositionLimits(
                x_min=_tbl_min_xyz[0] + _tbl_margin,
                x_max=_tbl_max_xyz[0] - _tbl_margin,
                y_min=_tbl_min_xyz[1] + _tbl_margin,
                y_max=_tbl_max_xyz[1] - _tbl_margin,
            )
        )

        scene = Scene(
            assets=[
                background,
                ground_plane,
                light,
                tabletop_anchor,
                avocado_obj,
                bowl_obj,
                broccoli_obj,
                sweet_potato_obj,
                red_bell_pepper_obj,
            ]
        )

        # goal_added (enforced by PickAndPlaceTask success predicate):  in(avocado, bowl)
        # goal_removed (implicitly negated when the pick succeeds):  on(avocado, maple_table_robolab)

        return IsaacLabArenaEnvironment(
            name=self.name,
            embodiment=embodiment,
            scene=scene,
            task=PickAndPlaceTask(
                pick_up_object=avocado_obj,
                destination_location=bowl_obj,
                background_scene=background,
                episode_length_s=20.0,
                task_description="Pick up the avocado from the table and place it in the bowl.",
            ),
        )

    @staticmethod
    def add_cli_args(parser: argparse.ArgumentParser) -> None:
        parser.add_argument("--embodiment", type=str, default="franka_ik")
