# Copyright (c) 2025-2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

"""Auto-generated by isaaclab_arena.llm_env_gen.

Task: Open the microwave door on a table, with vegetable distractors on the table outside the microwave.

Task wiring: OpenDoorTask: openable=microwave
"""

from __future__ import annotations

import argparse
from typing import TYPE_CHECKING

from isaaclab_arena.assets.register import register_environment
from isaaclab_arena_environments.example_environment_base import ExampleEnvironmentBase

if TYPE_CHECKING:
    from isaaclab_arena.environments.isaaclab_arena_environment import IsaacLabArenaEnvironment


@register_environment
class MicrowaveOpenTableEnvironment(ExampleEnvironmentBase):
    """Open the microwave door on a table, with vegetable distractors on the table outside the microwave."""

    name: str = "microwaveOpentable"

    def get_env(self, args_cli: argparse.Namespace) -> IsaacLabArenaEnvironment:
        from isaaclab_arena.assets.object_base import ObjectType
        from isaaclab_arena.assets.object_reference import ObjectReference
        from isaaclab_arena.environments.isaaclab_arena_environment import IsaacLabArenaEnvironment
        from isaaclab_arena.relations.relations import IsAnchor, On, PositionLimits, RotateAroundSolution
        from isaaclab_arena.scene.scene import Scene
        from isaaclab_arena.tasks.open_door_task import OpenDoorTask
        from isaaclab_arena.utils.pose import Pose

        background = self.asset_registry.get_asset_by_name("maple_table_robolab")()
        background.set_initial_pose(Pose(position_xyz=(0.5, 0.0, 0.0), rotation_xyzw=(0.0, 0.0, 0.7071068, 0.7071068)))
        ground_plane = self.asset_registry.get_asset_by_name("ground_plane")()
        ground_plane.set_initial_pose(Pose(position_xyz=(0.0, 0.0, -1.05)))
        light = self.asset_registry.get_asset_by_name("light")()

        # Tabletop anchor — tabletop anchor = tabletop_anchor (ObjectReference sub-prim); PositionLimits derived from get_world_bounding_box().
        tabletop_anchor = ObjectReference(
            name="table",
            prim_path="{ENV_REGEX_NS}/maple_table_robolab/table",
            parent_asset=background,
            object_type=ObjectType.RIGID,
        )
        tabletop_anchor.add_relation(IsAnchor())

        # No kwargs — works for both no_embodiment and robot embodiments whose
        # optional flags (enable_cameras, etc.) default to safe values.
        embodiment = self.asset_registry.get_asset_by_name(args_cli.embodiment)()

        microwave_obj = self.asset_registry.get_asset_by_name("microwave")()
        broccoli_obj = self.asset_registry.get_asset_by_name("broccoli")()
        sweet_potato_obj = self.asset_registry.get_asset_by_name("sweet_potato")()
        red_bell_pepper_obj = self.asset_registry.get_asset_by_name("red_bell_pepper_objaverse_robolab")()

        # Runtime-derived XY footprint from the tabletop bbox — no
        # hardcoded bounds, works across tables of any size. The
        # bbox stores (N, 3) tensors; we squeeze to plain floats
        # for the first env since PositionLimits takes scalars and
        # the tabletop is static across envs.
        _tbl_bbox = tabletop_anchor.get_world_bounding_box()
        _tbl_min_xyz = [float(_tbl_bbox.min_point[0, i]) for i in range(3)]
        _tbl_max_xyz = [float(_tbl_bbox.max_point[0, i]) for i in range(3)]
        _tbl_margin = 0.05

        microwave_obj.add_relation(On(tabletop_anchor, clearance_m=0.02))
        microwave_obj.add_relation(
            PositionLimits(
                x_min=_tbl_min_xyz[0] + _tbl_margin,
                x_max=_tbl_max_xyz[0] - _tbl_margin,
                y_min=_tbl_min_xyz[1] + _tbl_margin,
                y_max=_tbl_max_xyz[1] - _tbl_margin,
            )
        )
        microwave_obj.add_relation(RotateAroundSolution(yaw_rad=-1.5707963267948966))
        broccoli_obj.add_relation(On(tabletop_anchor, clearance_m=0.02))
        broccoli_obj.add_relation(
            PositionLimits(
                x_min=_tbl_min_xyz[0] + _tbl_margin,
                x_max=_tbl_max_xyz[0] - _tbl_margin,
                y_min=_tbl_min_xyz[1] + _tbl_margin,
                y_max=_tbl_max_xyz[1] - _tbl_margin,
            )
        )
        # TODO(relation kind 'next_to' has no generator support yet): {'kind': 'next_to', 'subject': 'broccoli', 'target': 'microwave', 'params': {}}
        sweet_potato_obj.add_relation(On(tabletop_anchor, clearance_m=0.02))
        sweet_potato_obj.add_relation(
            PositionLimits(
                x_min=_tbl_min_xyz[0] + _tbl_margin,
                x_max=_tbl_max_xyz[0] - _tbl_margin,
                y_min=_tbl_min_xyz[1] + _tbl_margin,
                y_max=_tbl_max_xyz[1] - _tbl_margin,
            )
        )
        # TODO(relation kind 'next_to' has no generator support yet): {'kind': 'next_to', 'subject': 'sweet_potato', 'target': 'microwave', 'params': {}}
        red_bell_pepper_obj.add_relation(On(tabletop_anchor, clearance_m=0.02))
        red_bell_pepper_obj.add_relation(
            PositionLimits(
                x_min=_tbl_min_xyz[0] + _tbl_margin,
                x_max=_tbl_max_xyz[0] - _tbl_margin,
                y_min=_tbl_min_xyz[1] + _tbl_margin,
                y_max=_tbl_max_xyz[1] - _tbl_margin,
            )
        )
        # TODO(relation kind 'next_to' has no generator support yet): {'kind': 'next_to', 'subject': 'red_bell_pepper', 'target': 'microwave', 'params': {}}

        scene = Scene(
            assets=[
                background,
                ground_plane,
                light,
                tabletop_anchor,
                microwave_obj,
                broccoli_obj,
                sweet_potato_obj,
                red_bell_pepper_obj,
            ]
        )

        # goal_added: open(microwave, None) — enforced by OpenDoorTask success predicate
        # goal_removed (implied when door is opened): closed(microwave, None)

        return IsaacLabArenaEnvironment(
            name=self.name,
            embodiment=embodiment,
            scene=scene,
            task=OpenDoorTask(
                openable_object=microwave_obj,
                episode_length_s=30.0,
                task_description=(
                    "Open the microwave door on a table, with vegetable distractors on the table outside the microwave."
                ),
            ),
        )

    @staticmethod
    def add_cli_args(parser: argparse.ArgumentParser) -> None:
        parser.add_argument("--embodiment", type=str, default="franka_ik")
