# Copyright (c) 2025-2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

# This file shows how to configure the ReplayLerobotActionPolicy class for G1 locomanipulation task
dataset_path: /datasets/curobo_v3_with_camera_0403/lerobot/
action_horizon: 1

embodiment_tag: OXE_DROID
video_backend: decord
# Load modality config from the existing modality configs in GR00T
# modality_config_path:

policy_joints_config_path: isaaclab_arena_gr00t/embodiments/droid/gr00t_8dof_joint_space.yaml
action_joints_config_path: isaaclab_arena_gr00t/embodiments/droid/8dof_joint_space.yaml
action_chunk_length: 1

task_mode_name: droid_manipulation
